### ISSUE TITLE
Neither able to open in IDE / or is the container getting connected

### ISSUE THREAD

**Issue by zackerysmith** [codercom/bugs#113]
**Describe the bug**
I am unable to open project in IDE, nor the container getting connect.

**To Reproduce**
Steps to reproduce the behavior "Open in IDE":
1. Open Project in IDE

Steps to reproduce the behavior Container not connecting:
1. Open your container.

**Expected behavior**
User should be able to connect to the IDE.
User should have the access to the Container from terminal.

**Screenshots**
IDE Issue:
![image](https://user-images.githubusercontent.com/30194321/43992464-2753ad86-9d9c-11e8-83a4-bd36b96c428a.png)

Container Issue:
![image](https://user-images.githubusercontent.com/30194321/43992471-378b7378-9d9c-11e8-8978-34325e65be74.png)

**Comment by zackerysmith** [comment]
This is now resolved

**Comment by cjislegit** [comment]
Describe the bug
I am experiencing the IDE  issue mentioned above. My projects will not open.

To Reproduce
Open any Project in IDE

Expected behavior
User should be able to connect to the IDE.

Screenshot
<img width="386" alt="screen shot 2018-09-01 at 3 48 19 pm" src="https://user-images.githubusercontent.com/30734040/44950528-ba146f80-adfe-11e8-8189-980bddeda370.png">
