### ISSUE TITLE
Tmux error with zsh shell

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/bugs#160]
**Describe the bug**
User installed zsh and had tmux errors when he opened the terminal.

**To Reproduce**
1. Open IDE
2. Open terminal
3. Type `apt install zsh`
4. Then type `chsh -s /bin/zsh root`
5. Restart your container - turn off, then on again
6. Open terminal in the IDE
7. See the error `zsh:1: command not found: tmux`

**Expected behavior**
terminal to open and work without error

**Screenshots**
none at this time

**Desktop (please complete the following information):**
 - OS: Mac High Sierra and Windows 10
 - Browser: Chrome 
 - Version: 68

**Additional context**
```zendesk ticket 776```

**Comment by Mk-Chan** [comment]
Hi, just a minor correction, I had `restarted` the container at step 5 to produce the bug as opposed to `resetting` it which actually fixes the issue in a destructive, undesirable way.

**Comment by Mk-Chan** [comment]
It seems to me like a simple problem: in your preconfigured bashrc, or profile, you must be setting a path which is non standard and thus a new install of zsh would not capture the same since it won't source the bash config. In such a case, ideally it would be great if you would provide preconfigured popular shells such as bash, zsh, fish, ksh. The other alternatives would likely constitute removing the chsh capability or providing instructions (the latter of which could present you more complaints in the future). That's just my perspective though.

Personally I would love to be able to seamlessly install oh-my-zsh.

**Comment by jaymeramsay** [comment]
Thank you for finding my typo. I reproduced the issue by restarting not resetting. I'll correct.

**Comment by jaymeramsay** [comment]
We currently only have support for bash, but support for alternative shells is on the trajectory. I'm going to turn this into a feature request instead of a bug.

**Comment by jaymeramsay** [comment]
https://github.com/codercom/features/issues/105
