### ISSUE TITLE
Sign up with Google doesn't work on website

### ISSUE THREAD

**Issue by AaronPinto** [codercom/bugs#2]
When you hit sign up and enter in an alpha key and then hit sign up with Google, the window appears for you to select your Gmail account, but after you select it the window closes and nothing happens.

**Comment by nhuebecker** [comment]
Hey @AaronPinto I just registered with Google without a problem. Have you gotten this to work?

**Comment by AaronPinto** [comment]
Nope, I just tried it and still, nothing happens.

**Comment by Lichty** [comment]
Same story here.  The Google sign up didn't work on pc or mobile.  I made a non Google account and it worked fine.

**Comment by nhuebecker** [comment]
Interesting, what are your system specifications for the device you tried to sign up with?

Desktop (please complete the following information):

    OS: [e.g. iOS]
    Browser [e.g. chrome, safari]
    Version [e.g. 22]

Smartphone (please complete the following information):

    Device: [e.g. iPhone6]
    OS: [e.g. iOS8.1]
    Browser [e.g. stock browser, safari]
    Version [e.g. 22]

**Comment by AaronPinto** [comment]
OS: Windows 10 Insider Preview Build 17713
Browser: Chrome 
Version: 67.0.3396.99 (Official Build) (64-bit)

**Comment by nhuebecker** [comment]
Weird, I just got it to work on the same system. Can you screen-record what happens and share that?

**Comment by nhuebecker** [comment]
Weird, I just got it to work on the same system. Can you screen-record what happens and share that?

**Comment by AaronPinto** [comment]
Yep
[2018-07-24 12-44-14.zip](https://github.com/codercom/bugs/files/2224567/2018-07-24.12-44-14.zip)

**Comment by Lichty** [comment]
Mobile:
Galaxy S7 edge

OS: Android 8.0.0; Samsung-SM-G935A Build/R16NW
Chrome: 67.0.3396.87

PC
OS: Windows NT: 10.0.17134 (Windows 10)
Chome: 67.0.3396.99

On Jul 24, 2018 8:02 AM, "Nikolas Huebecker" <notifications@github.com>
wrote:

Interesting, what are your system specifications for the device you tried
to sign up with?

Desktop (please complete the following information):

OS: [e.g. iOS]
Browser [e.g. chrome, safari]
Version [e.g. 22]

Smartphone (please complete the following information):

Device: [e.g. iPhone6]
OS: [e.g. iOS8.1]
Browser [e.g. stock browser, safari]
Version [e.g. 22]

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/codercom/bugs/issues/2#issuecomment-407439378>, or mute
the thread

**Comment by lobsterhands** [comment]
Thank you @AaronPinto , @nhuebecker , and @Lichty for the information. From details here and other feedback, it seems the issue is isolated to users who are on Windows 10.
