### ISSUE TITLE
Support for Docker

### ISSUE THREAD

**Issue by iamshouvikmitra** [codercom/bugs#225]
Describe the bug

To Reproduce
Install Docker according to official instructions.

Expected behavior
Command 'docker' should be available at command prompt.

Screenshots
N/A

Desktop (please complete the following information):
N/A

Smartphone (please complete the following information):
N/A

Additional context
One should be able to install Docker, but it needs a way to be added to services and boot sequence to start automatically in the container.

**Comment by deansheather** [comment]
At the moment you cannot run Docker on Coder. With the container technology we use it's technically possible for us to allow things like Docker to run in user containers, but we block some of the things that Docker requires for security reasons.

We should be changing this very soon so that users can run Docker daemon inside their container.

**Comment by nol166** [comment]
Moving this to /features
