### ISSUE TITLE
Dashboard: Projects: Clicking on the project name 'edit' button results in error (FF)

### ISSUE THREAD

**Issue by jaentwistle** [codercom/bugs#28]
Via Zendesk

"Clicking on the edit button for the project name results in "event is not defined" error."

**Comment by lobsterhands** [comment]
**Describe the bug**
In Firefox, clicking on the project name 'edit' button results in an `event is not defined` error.

**To Reproduce**
Steps to reproduce the behavior:
1. Open Coder in Firefox
2. Navigate to the Dashboard Projects page
3. Expand a project and click on the 'edit' name button
4. Nothing happens; check your console for the error

**Expected behavior**
I expect the project name input field to be focused and ready for editing.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux & Windows10
 - Browser: Firefox
 - Version: 61.0.1 (64-bit)

**Comment by lobsterhands** [comment]
A fix for this issue has been deployed.
