### ISSUE TITLE
ChromeOS: Esc doesn't work to exit insert mode in VIM

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#362]
Mar 22, 2019 at 10:26:46 AM
**Describe the bug**
A user has reported the escape key doesn't function correctly in VIM to exit insert mode

**Environment**
Production

**To Reproduce**
1. Open a terminal
2. Run VIM
3. Press `i` to start insert mode
4. Press escape
5. Notice that you are still in insert mode

**Expected behavior**
Escape causes VIM to exit insert mode

**Desktop**
ChromeOS

**Comment by 123satchipanda** [comment]
Hello @nol166,

Thank you for adding this bug issue.

However, I've found the fix to this.

This was happening because I had the browser extension, [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb), on.

I've disabled the extension for ide.coder.com, and it was working as expected :)

I'm sorry for taking your time to look into this!

**Comment by nol166** [comment]
@123satchipanda No worries, Thanks for the update.
