### ISSUE TITLE
Dashboard: Containers: Terminal: Highlighting Visual Issue

### ISSUE THREAD

**Issue by jaentwistle** [codercom/bugs#5]
via zendesk 
https://imgur.com/a/Jb08tYl

**Comment by lobsterhands** [comment]
**Describe the bug**
On initial load of the [containers](https://coder.com/dashboard/containers) page, text selection completely obscures the selected text.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to the [containers](https://coder.com/dashboard/containers) page
2. Ensure your container is turned on
3. Click and drag to select text in the terminal
4. You should see that your text is obscured by the selection

**Expected behavior**
Selected text is still visible.

**Screenshots**
![screenshot from 2018-07-24 11-21-42](https://user-images.githubusercontent.com/1688881/43152273-c30c9782-8f33-11e8-8ce6-190f0ea3be9b.png)
**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Chrome
 - Version: Version 64.0.3282.119 (Official Build) (64-bit)

**Additional context**
Changing the theme (click your user account icon in the top right and Select Theme) corrects the issue until the next page refresh.

**Comment by jaymeramsay** [comment]
this is still a valid issue.
